theme: jekyll-theme-cayman
title: My CodeCave
description: Bookmark this to keep an eye on my project updates!

colors:
  gradient_left: "#155799"
  gradient_right: "#159957"
  header: "#ff0"

exclude:
  - "package.json"
  - "run.sh"
  - "vendor"

plugins: [jekyll-mermaid]
